/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com.snail.device_jni_PropertiesGet */

#ifndef _Included_com.snail.antifake_jni_PropertiesGet
#define _Included_com.snail.antifake_jni_PropertiesGet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com.snail.device_jni_PropertiesGet
 * Method:    native_get
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_snail_antifake_jni_PropertiesGet_native_1get__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com.snail.device_jni_PropertiesGet
 * Method:    native_get
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_snail_antifake_jni_PropertiesGet_native_1get__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
