/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <sys/system_properties.h>
#include <android/log.h>
#include <string.h>


#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,"lishang",__VA_ARGS__)


JNIEXPORT jstring JNICALL
proGetSS
        (JNIEnv *env, jclass clazz, jstring keyJ, jstring defJ) {
    int len;
    const char *key;
    char buf[100];
    jstring rvJ = NULL;

    if (keyJ == NULL) {
        LOGI("key must not be null.");
        goto error;
    }

    key = (*env)->GetStringUTFChars(env, keyJ, NULL);

    len = __system_property_get(key, buf);
    if ((len <= 0) && (defJ != NULL)) {
        rvJ = defJ;
    } else if (len >= 0) {
        rvJ = (*env)->NewStringUTF(env, buf);
    } else {
        rvJ = (*env)->NewStringUTF(env, "");
    }

    (*env)->ReleaseStringUTFChars(env, keyJ, key);

    error:
    return rvJ;
}


JNIEXPORT jstring JNICALL
    proGet(JNIEnv *env, jclass clazz, jstring keyJ) {
    return proGetSS(env, clazz, keyJ, NULL);
}


static int registerNativeMethods(JNIEnv *env, const char *className,
                                 JNINativeMethod *gMethods, int numMethods) {
    jclass clazz;

    clazz = (*env)->FindClass(env, className);
    if (clazz == NULL)
        return JNI_FALSE;

    if ((*env)->RegisterNatives(env, clazz, gMethods, numMethods) < 0) {
        return JNI_FALSE;
    }
    return JNI_TRUE;
}
static const char *classPathName = "com/snail/antifake/jni/PropertiesGet";

static JNINativeMethod methods[] = {
        {"native_get", "(Ljava/lang/String;)Ljava/lang/String;", (void *) proGet},
        {"native_get", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;", (void *) proGetSS},

};

jint JNI_OnLoad(JavaVM* vm, void* reserved)
{
    JNIEnv* env = NULL;
    jint result = -1;

    if ((*vm)->GetEnv(vm, (void**) &env, JNI_VERSION_1_4) != JNI_OK)
        goto bail;

    if (!registerNativeMethods(env, classPathName, methods, sizeof(methods)/sizeof(methods[0])))
        goto bail;

    result = JNI_VERSION_1_4;

    bail:
    //LOGI("Leaving JNI_OnLoad (result=0x%x)\n", result);
    return result;
}
