/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com.snail.device_jni_EmulatorDetectUtil */

#ifndef _Included_com.snail.antifake_jni_EmulatorDetectUtil
#define _Included_com.snail.antifake_jni_EmulatorDetectUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com.snail.device_jni_EmulatorDetectUtil
 * Method:    detect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_snail_antifake_jni_EmulatorDetectUtil_detect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
